package:
  name:ipyReload
  version:0.01.00

source:
  git_rev:v0.13.1 
  git_url:https://github.com/wolfiex/ipython-dev-reload

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:ipyReload
    -

about:
  home:
  license:MIT
  license_file:LICENSE
