package:
  name: ipyreload
  version: '1.2.1'

source:
  git_rev: 1.2.1
  git_url: https://github.com/wolfiex/ipython-dev-reload.git

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - ipython

about:
  home: https://github.com/wolfiex/ipython-dev-reload
  license: MIT
  license_file: LICENSE
